baseURL = 'https://jon-fox.github.io/'
languageCode = 'en-us'
title = 'Jon Fox - Machine Learning Engineer'
theme = 'ananke'

[params]
description = 'Portfolio of Jon Fox - Machine Learning Engineer specializing in Applied AI Applications with backend and frontend experience'
author = 'Jon Fox'
custom_css = ['css/custom.css']

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Projects'
pageRef = '/projects'
weight = 20

[[menu.main]]
name = 'About'
pageRef = '/about'
weight = 30
